Migrate B2B Aura to B2B LWR
Adyen/adyen-salesforce-b2b-lightning pull request #31
Opened 2024-03-27 09:20 UTC by dcardos

## Summary
Implementing new LWC component for Adyen drop in checkout
Implementing async notification handler
Implementing exception treatment 
Including unit tests

2024-03-27 13:00 UTC, ShubhamVijaivargiya requested changes
Can we add static resource files into package?

2024-03-27 13:20 UTC, ShubhamVijaivargiya requested changes

2024-03-27 13:20 UTC, ShubhamVijaivargiya commented on force-app/main/default/classes/AdyenB2BConstants.cls
> +    public static final String ADYEN_LIBRARY_VERSION_FOR_APP_INFO = '3.0.0';
Since we have already released 3.0.1.1, can we change this to 3.1.0.0 if possible? Else we can also jump to next major version.

2024-03-27 13:26 UTC, dcardos commented on force-app/main/default/classes/AdyenB2BConstants.cls
> +    public static final String ADYEN_LIBRARY_VERSION_FOR_APP_INFO = '3.0.0';
I usually deploy the updated version along with the updated sfdx-package.json with the new package ids. But always good to remember.

2024-03-28 08:49 UTC, ShubhamVijaivargiya approved these changes

2024-03-28 08:51 UTC, merged