E2E test workflow
Adyen/adyen-salesforce-b2b-lightning pull request #52
Opened 2024-07-16 12:34 UTC by shubhamk67

Added e2e tests for b2b lightning.
Added GitHub Actions workflow.
Added script to update custom metadata before deployment.

2024-07-17 13:54 UTC, dcardos requested changes
Nice work, small changes that can be discussed.

2024-07-17 13:54 UTC, dcardos commented on .github/workflows/e2e-tests.yml
> +      - name: Run Apex tests
I believe this step is redundant if the unit test script is already checking this.

2024-07-17 13:54 UTC, dcardos commented on .github/workflows/e2e-tests.yml
> +  e2e-testing:
All good, but to keep consistency and facilitate the reading, would be nice to have blank lines in between the steps.

2024-07-17 14:27 UTC, dcardos approved these changes

2024-07-17 14:55 UTC, dcardos approved these changes

2024-07-19 12:05 UTC, zenit2001 approved these changes

2024-07-19 13:49 UTC, merged