Extend payments call - PW6909
Adyen/adyen-salesforce-b2b-lightning pull request #6
Opened 2022-07-23 04:10 UTC by vkuncham

## Summary

## Tested scenarios

**Fixed issue**:

2022-07-25 13:30 UTC, ShubhamVijaivargiya commented on adyen-appexchange/main/default/classes/AdyenPaymentUtility.cls
> +        String merchantAccountName = TEST_MERCHANT_ACCOUNT;
Single quotes are missing?

2022-07-25 13:32 UTC, ShubhamVijaivargiya requested changes
Please address review comments.

2022-07-25 16:46 UTC, ShubhamVijaivargiya approved these changes

2022-07-26 07:34 UTC, maassenbas approved these changes

2022-07-26 18:29 UTC, vkuncham commented on adyen-appexchange/main/default/classes/AdyenPaymentUtility.cls
> +            if (skipMerchantAccount) {
To test for a failed capture request, we want a blank value in the merchantAccount field, however this is part of the custom metadata that is queried in this method, we cannot update custom metadata through code, hence leveraging this boolean variable to set the merchantAccount name based on the scenario we are testing.

2022-07-26 18:29 UTC, vkuncham commented on adyen-appexchange/main/default/classes/AdyenPaymentUtility.cls
> +        String merchantAccountName = TEST_MERCHANT_ACCOUNT;
Fixed.

2022-08-01 15:49 UTC, merged