PW-6570 and PW-6953 - Refactored webhook handler code and defined constants for package names and package versions for app info
Adyen/adyen-salesforce-b2b-lightning pull request #7
Opened 2022-07-29 16:07 UTC by ShubhamVijaivargiya

## Summary
1. Refactored webhook handler code 
2. Defined constants for package name and package version for app info
## Tested scenarios

**Fixed issue**:

2022-08-01 01:01 UTC, vkuncham commented
Can you remove .idea folder from the PR as we need to push it to the repo?

2022-08-01 01:34 UTC, vkuncham commented on adyen-appexchange/main/default/classes/AdyenWebhookNotificationHelper.cls
> +    public static String TEST_NOTIFICATION_REQUEST_BODY;
@testvisible is not needed for public variables. It is only needed for private variables.

2022-08-01 01:39 UTC, vkuncham commented on adyen-appexchange/main/default/classes/AdyenPaymentUtility.cls
> +    public static final String EXTERNAL_PLATFORM_NAME_FOR_APPINFO = 'Salesforce B2B Lightning';
This comment is for the lines 11 through 15.  Instead of hard-coding the values in the method, now we declared variables and referring to those variables in the method. Is there any advantage to storing this info as custom metadata and referring in the method? Anytime we release a new version, we have to modify these variables or modify the values directly in the method (if we keep existing approach) in this file vs we can update the custom metadata record. Thoughts?

2022-08-01 01:40 UTC, vkuncham requested changes
Please take a look at my review comments.

2022-08-01 02:16 UTC, vkuncham commented on adyen-appexchange/main/default/classes/AdyenWebhookNotificationHelper.cls
> +        System.debug('---->Entering AdyenPaymentHelper.handleAsyncNotificationCallback PaymentGatewayNotificationContext = ' + gatewayNotificationContext);
Should say --->**Entering AdyenWebhookNotificationHelper.handleAsyncNotificationCallback** . This applies to 44, 62 and 125 as well.

2022-08-01 02:25 UTC, vkuncham requested changes
More comments.

2022-08-01 18:54 UTC, vkuncham commented
@ShubhamVijaivargiya The changes look good. I just have few questions: a) Were you able to run the test classes and see the code coverage? 2) I left comments about leveraging custom metadata for package versions and names. What were your thoughts about it? 3) Can you resolve the conflicts caused when I merged this PR: https://github.com/Adyen/adyen-salesforce-b2b-lightning/pull/6

2022-08-05 07:27 UTC, vkuncham approved these changes

2022-08-18 15:51 UTC, maassenbas approved these changes

2022-08-18 18:31 UTC, merged